services:
  - type: web
    name: food-for-brain
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: food-for-brain-db
          property: connectionString
      - key: CLIENT_URL
        fromService:
          type: web
          name: food-for-brain
          property: host
    autoDeploy: false

databases:
  - name: food-for-brain-db
    databaseName: food_for_brain
    user: food_brain_user
    plan: free